plugins {
    id 'java'
    id 'application'
    id 'jacoco'
}

jacocoTestReport {
    dependsOn test
    reports {
        csv.required = true
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.mockito:mockito-core:5.18.0'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // Mockito
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.11.0'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // SQLite
    implementation 'org.xerial:sqlite-jdbc:3.51.2.0'
}

test {
    useJUnitPlatform()
    ignoreFailures = true
}

application {
    mainClass = 'TopSecret'
}

tasks.named('run', JavaExec) {
    standardInput = System.in
}
